version: '3.9'

networks:
  wordpress-network:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    init: true
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: mariadb
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - wordpress-network

  redis:
    container_name: redis
    build: requirements/bonus/redis
    init: true
    ports:
      - "6379:6379"
    restart: always
    networks:
      - wordpress-network

  nginx:
    container_name: nginx
    build: requirements/nginx
    init: true
    ports:
      - "443:443"
    volumes:
      - type: volume
        source: wordpress
        target: /var/www/html
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    networks:
      - wordpress-network

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    init: true
    volumes:
      - type: volume
        source: wordpress
        target: /var/www/html
    restart: always
    ports:
      - "9000:9000"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      REDIS_HOST: ${REDIS_HOST}
    networks:
      - wordpress-network

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/fyuta/data/mariadb/'

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/fyuta/data/wordpress/src'
